# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Eri"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_V2"]'
      shield: '["eri", "eri_left"]'
